-- Kisan Mela: canonical state normalization + robust dedup support (one migration for all
-- schema/data changes in this work — spec: docs/KISAN_MELA_DEDUP_STATE_PROMPT.md).
-- Idempotent: safe to run even if parts were applied during development via `db query`.

-- ===========================================================================================
-- Phase 1 — canonical state backfill
-- The authoritative normaliser is src/content/states.js (applied at every entry point). This
-- SQL mirrors its key() (lowercase; keep only latin alphanumerics + Devanagari) and alias map so
-- EVERY existing state value in kisan_mela + kisan_mela_candidates is folded to its canonical name
-- here too (1d). The one-time cleanup script re-runs the same normaliser and logs any unmappable value.
-- ===========================================================================================

create or replace function public._mela_state_key(txt text) returns text
  language sql immutable as $$
  select regexp_replace(lower(coalesce(txt, '')), '[^a-z0-9ऀ-ॿ]', '', 'g');
$$;

with aliases(k, canonical) as (values
    ('andhrapradesh', 'Andhra Pradesh'),
    ('आंध्रप्रदेश', 'Andhra Pradesh'),
    ('ap', 'Andhra Pradesh'),
    ('आन्ध्रप्रदेश', 'Andhra Pradesh'),
    ('arunachalpradesh', 'Arunachal Pradesh'),
    ('अरुणाचलप्रदेश', 'Arunachal Pradesh'),
    ('ar', 'Arunachal Pradesh'),
    ('arunachal', 'Arunachal Pradesh'),
    ('assam', 'Assam'),
    ('असम', 'Assam'),
    ('as', 'Assam'),
    ('bihar', 'Bihar'),
    ('बिहार', 'Bihar'),
    ('br', 'Bihar'),
    ('chhattisgarh', 'Chhattisgarh'),
    ('छत्तीसगढ़', 'Chhattisgarh'),
    ('cg', 'Chhattisgarh'),
    ('chattisgarh', 'Chhattisgarh'),
    ('छत्तीसगढ', 'Chhattisgarh'),
    ('छग', 'Chhattisgarh'),
    ('goa', 'Goa'),
    ('गोवा', 'Goa'),
    ('ga', 'Goa'),
    ('gujarat', 'Gujarat'),
    ('गुजरात', 'Gujarat'),
    ('gj', 'Gujarat'),
    ('haryana', 'Haryana'),
    ('हरियाणा', 'Haryana'),
    ('hr', 'Haryana'),
    ('himachalpradesh', 'Himachal Pradesh'),
    ('हिमाचलप्रदेश', 'Himachal Pradesh'),
    ('hp', 'Himachal Pradesh'),
    ('हिप्र', 'Himachal Pradesh'),
    ('jharkhand', 'Jharkhand'),
    ('झारखंड', 'Jharkhand'),
    ('jh', 'Jharkhand'),
    ('झारखण्ड', 'Jharkhand'),
    ('karnataka', 'Karnataka'),
    ('कर्नाटक', 'Karnataka'),
    ('ka', 'Karnataka'),
    ('कर्णाटक', 'Karnataka'),
    ('kerala', 'Kerala'),
    ('केरल', 'Kerala'),
    ('kl', 'Kerala'),
    ('केरला', 'Kerala'),
    ('madhyapradesh', 'Madhya Pradesh'),
    ('मध्यप्रदेश', 'Madhya Pradesh'),
    ('mp', 'Madhya Pradesh'),
    ('मप्र', 'Madhya Pradesh'),
    ('maharashtra', 'Maharashtra'),
    ('महाराष्ट्र', 'Maharashtra'),
    ('mh', 'Maharashtra'),
    ('maharastra', 'Maharashtra'),
    ('manipur', 'Manipur'),
    ('मणिपुर', 'Manipur'),
    ('mn', 'Manipur'),
    ('meghalaya', 'Meghalaya'),
    ('मेघालय', 'Meghalaya'),
    ('ml', 'Meghalaya'),
    ('mizoram', 'Mizoram'),
    ('मिज़ोरम', 'Mizoram'),
    ('mz', 'Mizoram'),
    ('मिजोरम', 'Mizoram'),
    ('nagaland', 'Nagaland'),
    ('नागालैंड', 'Nagaland'),
    ('nl', 'Nagaland'),
    ('नागालैण्ड', 'Nagaland'),
    ('odisha', 'Odisha'),
    ('ओडिशा', 'Odisha'),
    ('or', 'Odisha'),
    ('od', 'Odisha'),
    ('orissa', 'Odisha'),
    ('ओड़िशा', 'Odisha'),
    ('उड़ीसा', 'Odisha'),
    ('punjab', 'Punjab'),
    ('पंजाब', 'Punjab'),
    ('pb', 'Punjab'),
    ('rajasthan', 'Rajasthan'),
    ('राजस्थान', 'Rajasthan'),
    ('rj', 'Rajasthan'),
    ('sikkim', 'Sikkim'),
    ('सिक्किम', 'Sikkim'),
    ('sk', 'Sikkim'),
    ('tamilnadu', 'Tamil Nadu'),
    ('तमिलनाडु', 'Tamil Nadu'),
    ('tn', 'Tamil Nadu'),
    ('तमिलनाडू', 'Tamil Nadu'),
    ('telangana', 'Telangana'),
    ('तेलंगाना', 'Telangana'),
    ('ts', 'Telangana'),
    ('tg', 'Telangana'),
    ('तेलंगाणा', 'Telangana'),
    ('तेलुगु', 'Telangana'),
    ('tripura', 'Tripura'),
    ('त्रिपुरा', 'Tripura'),
    ('tr', 'Tripura'),
    ('uttarpradesh', 'Uttar Pradesh'),
    ('उत्तरप्रदेश', 'Uttar Pradesh'),
    ('up', 'Uttar Pradesh'),
    ('उप्र', 'Uttar Pradesh'),
    ('uttarakhand', 'Uttarakhand'),
    ('उत्तराखंड', 'Uttarakhand'),
    ('uk', 'Uttarakhand'),
    ('ua', 'Uttarakhand'),
    ('uttaranchal', 'Uttarakhand'),
    ('उत्तराखण्ड', 'Uttarakhand'),
    ('उत्तरांचल', 'Uttarakhand'),
    ('westbengal', 'West Bengal'),
    ('पश्चिमबंगाल', 'West Bengal'),
    ('wb', 'West Bengal'),
    ('bengal', 'West Bengal'),
    ('पबंगाल', 'West Bengal'),
    ('andamanandnicobarislands', 'Andaman and Nicobar Islands'),
    ('अंडमानऔरनिकोबारद्वीपसमूह', 'Andaman and Nicobar Islands'),
    ('an', 'Andaman and Nicobar Islands'),
    ('andamannicobar', 'Andaman and Nicobar Islands'),
    ('andamanandnicobar', 'Andaman and Nicobar Islands'),
    ('अंडमाननिकोबार', 'Andaman and Nicobar Islands'),
    ('अंडमानऔरनिकोबार', 'Andaman and Nicobar Islands'),
    ('chandigarh', 'Chandigarh'),
    ('चंडीगढ़', 'Chandigarh'),
    ('ch', 'Chandigarh'),
    ('chandigarhut', 'Chandigarh'),
    ('चंडीगढ', 'Chandigarh'),
    ('चण्डीगढ़', 'Chandigarh'),
    ('dadraandnagarhavelianddamananddiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दादराऔरनगरहवेलीऔरदमनऔरदीव', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dn', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dd', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dnh', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dadraandnagarhaveli', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('damananddiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dadranagarhaveli', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('damandiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दादराऔरनगरहवेली', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दमनऔरदीव', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('delhi', 'Delhi'),
    ('दिल्ली', 'Delhi'),
    ('dl', 'Delhi'),
    ('nctofdelhi', 'Delhi'),
    ('nct', 'Delhi'),
    ('newdelhi', 'Delhi'),
    ('nationalcapitalterritoryofdelhi', 'Delhi'),
    ('नईदिल्ली', 'Delhi'),
    ('दिल्लीएनसीटी', 'Delhi'),
    ('jammuandkashmir', 'Jammu and Kashmir'),
    ('जम्मूऔरकश्मीर', 'Jammu and Kashmir'),
    ('jk', 'Jammu and Kashmir'),
    ('jammukashmir', 'Jammu and Kashmir'),
    ('जम्मूकश्मीर', 'Jammu and Kashmir'),
    ('जम्मूवकश्मीर', 'Jammu and Kashmir'),
    ('ladakh', 'Ladakh'),
    ('लद्दाख', 'Ladakh'),
    ('la', 'Ladakh'),
    ('लदाख', 'Ladakh'),
    ('lakshadweep', 'Lakshadweep'),
    ('लक्षद्वीप', 'Lakshadweep'),
    ('ld', 'Lakshadweep'),
    ('puducherry', 'Puducherry'),
    ('पुडुचेरी', 'Puducherry'),
    ('py', 'Puducherry'),
    ('pondicherry', 'Puducherry'),
    ('pondy', 'Puducherry'),
    ('पांडिचेरी', 'Puducherry'),
    ('पॉन्डिचेरी', 'Puducherry')
)
update public.kisan_mela km set state = a.canonical
  from aliases a
  where public._mela_state_key(km.state) = a.k and km.state is distinct from a.canonical;

with aliases(k, canonical) as (values
    ('andhrapradesh', 'Andhra Pradesh'),
    ('आंध्रप्रदेश', 'Andhra Pradesh'),
    ('ap', 'Andhra Pradesh'),
    ('आन्ध्रप्रदेश', 'Andhra Pradesh'),
    ('arunachalpradesh', 'Arunachal Pradesh'),
    ('अरुणाचलप्रदेश', 'Arunachal Pradesh'),
    ('ar', 'Arunachal Pradesh'),
    ('arunachal', 'Arunachal Pradesh'),
    ('assam', 'Assam'),
    ('असम', 'Assam'),
    ('as', 'Assam'),
    ('bihar', 'Bihar'),
    ('बिहार', 'Bihar'),
    ('br', 'Bihar'),
    ('chhattisgarh', 'Chhattisgarh'),
    ('छत्तीसगढ़', 'Chhattisgarh'),
    ('cg', 'Chhattisgarh'),
    ('chattisgarh', 'Chhattisgarh'),
    ('छत्तीसगढ', 'Chhattisgarh'),
    ('छग', 'Chhattisgarh'),
    ('goa', 'Goa'),
    ('गोवा', 'Goa'),
    ('ga', 'Goa'),
    ('gujarat', 'Gujarat'),
    ('गुजरात', 'Gujarat'),
    ('gj', 'Gujarat'),
    ('haryana', 'Haryana'),
    ('हरियाणा', 'Haryana'),
    ('hr', 'Haryana'),
    ('himachalpradesh', 'Himachal Pradesh'),
    ('हिमाचलप्रदेश', 'Himachal Pradesh'),
    ('hp', 'Himachal Pradesh'),
    ('हिप्र', 'Himachal Pradesh'),
    ('jharkhand', 'Jharkhand'),
    ('झारखंड', 'Jharkhand'),
    ('jh', 'Jharkhand'),
    ('झारखण्ड', 'Jharkhand'),
    ('karnataka', 'Karnataka'),
    ('कर्नाटक', 'Karnataka'),
    ('ka', 'Karnataka'),
    ('कर्णाटक', 'Karnataka'),
    ('kerala', 'Kerala'),
    ('केरल', 'Kerala'),
    ('kl', 'Kerala'),
    ('केरला', 'Kerala'),
    ('madhyapradesh', 'Madhya Pradesh'),
    ('मध्यप्रदेश', 'Madhya Pradesh'),
    ('mp', 'Madhya Pradesh'),
    ('मप्र', 'Madhya Pradesh'),
    ('maharashtra', 'Maharashtra'),
    ('महाराष्ट्र', 'Maharashtra'),
    ('mh', 'Maharashtra'),
    ('maharastra', 'Maharashtra'),
    ('manipur', 'Manipur'),
    ('मणिपुर', 'Manipur'),
    ('mn', 'Manipur'),
    ('meghalaya', 'Meghalaya'),
    ('मेघालय', 'Meghalaya'),
    ('ml', 'Meghalaya'),
    ('mizoram', 'Mizoram'),
    ('मिज़ोरम', 'Mizoram'),
    ('mz', 'Mizoram'),
    ('मिजोरम', 'Mizoram'),
    ('nagaland', 'Nagaland'),
    ('नागालैंड', 'Nagaland'),
    ('nl', 'Nagaland'),
    ('नागालैण्ड', 'Nagaland'),
    ('odisha', 'Odisha'),
    ('ओडिशा', 'Odisha'),
    ('or', 'Odisha'),
    ('od', 'Odisha'),
    ('orissa', 'Odisha'),
    ('ओड़िशा', 'Odisha'),
    ('उड़ीसा', 'Odisha'),
    ('punjab', 'Punjab'),
    ('पंजाब', 'Punjab'),
    ('pb', 'Punjab'),
    ('rajasthan', 'Rajasthan'),
    ('राजस्थान', 'Rajasthan'),
    ('rj', 'Rajasthan'),
    ('sikkim', 'Sikkim'),
    ('सिक्किम', 'Sikkim'),
    ('sk', 'Sikkim'),
    ('tamilnadu', 'Tamil Nadu'),
    ('तमिलनाडु', 'Tamil Nadu'),
    ('tn', 'Tamil Nadu'),
    ('तमिलनाडू', 'Tamil Nadu'),
    ('telangana', 'Telangana'),
    ('तेलंगाना', 'Telangana'),
    ('ts', 'Telangana'),
    ('tg', 'Telangana'),
    ('तेलंगाणा', 'Telangana'),
    ('तेलुगु', 'Telangana'),
    ('tripura', 'Tripura'),
    ('त्रिपुरा', 'Tripura'),
    ('tr', 'Tripura'),
    ('uttarpradesh', 'Uttar Pradesh'),
    ('उत्तरप्रदेश', 'Uttar Pradesh'),
    ('up', 'Uttar Pradesh'),
    ('उप्र', 'Uttar Pradesh'),
    ('uttarakhand', 'Uttarakhand'),
    ('उत्तराखंड', 'Uttarakhand'),
    ('uk', 'Uttarakhand'),
    ('ua', 'Uttarakhand'),
    ('uttaranchal', 'Uttarakhand'),
    ('उत्तराखण्ड', 'Uttarakhand'),
    ('उत्तरांचल', 'Uttarakhand'),
    ('westbengal', 'West Bengal'),
    ('पश्चिमबंगाल', 'West Bengal'),
    ('wb', 'West Bengal'),
    ('bengal', 'West Bengal'),
    ('पबंगाल', 'West Bengal'),
    ('andamanandnicobarislands', 'Andaman and Nicobar Islands'),
    ('अंडमानऔरनिकोबारद्वीपसमूह', 'Andaman and Nicobar Islands'),
    ('an', 'Andaman and Nicobar Islands'),
    ('andamannicobar', 'Andaman and Nicobar Islands'),
    ('andamanandnicobar', 'Andaman and Nicobar Islands'),
    ('अंडमाननिकोबार', 'Andaman and Nicobar Islands'),
    ('अंडमानऔरनिकोबार', 'Andaman and Nicobar Islands'),
    ('chandigarh', 'Chandigarh'),
    ('चंडीगढ़', 'Chandigarh'),
    ('ch', 'Chandigarh'),
    ('chandigarhut', 'Chandigarh'),
    ('चंडीगढ', 'Chandigarh'),
    ('चण्डीगढ़', 'Chandigarh'),
    ('dadraandnagarhavelianddamananddiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दादराऔरनगरहवेलीऔरदमनऔरदीव', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dn', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dd', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dnh', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dadraandnagarhaveli', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('damananddiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('dadranagarhaveli', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('damandiu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दादराऔरनगरहवेली', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('दमनऔरदीव', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('delhi', 'Delhi'),
    ('दिल्ली', 'Delhi'),
    ('dl', 'Delhi'),
    ('nctofdelhi', 'Delhi'),
    ('nct', 'Delhi'),
    ('newdelhi', 'Delhi'),
    ('nationalcapitalterritoryofdelhi', 'Delhi'),
    ('नईदिल्ली', 'Delhi'),
    ('दिल्लीएनसीटी', 'Delhi'),
    ('jammuandkashmir', 'Jammu and Kashmir'),
    ('जम्मूऔरकश्मीर', 'Jammu and Kashmir'),
    ('jk', 'Jammu and Kashmir'),
    ('jammukashmir', 'Jammu and Kashmir'),
    ('जम्मूकश्मीर', 'Jammu and Kashmir'),
    ('जम्मूवकश्मीर', 'Jammu and Kashmir'),
    ('ladakh', 'Ladakh'),
    ('लद्दाख', 'Ladakh'),
    ('la', 'Ladakh'),
    ('लदाख', 'Ladakh'),
    ('lakshadweep', 'Lakshadweep'),
    ('लक्षद्वीप', 'Lakshadweep'),
    ('ld', 'Lakshadweep'),
    ('puducherry', 'Puducherry'),
    ('पुडुचेरी', 'Puducherry'),
    ('py', 'Puducherry'),
    ('pondicherry', 'Puducherry'),
    ('pondy', 'Puducherry'),
    ('पांडिचेरी', 'Puducherry'),
    ('पॉन्डिचेरी', 'Puducherry')
)
update public.kisan_mela_candidates kc set raw_state = a.canonical
  from aliases a
  where kc.raw_state is not null
    and public._mela_state_key(kc.raw_state) = a.k and kc.raw_state is distinct from a.canonical;

-- ===========================================================================================
-- Phase 2 — geocode precision (2a-i): trust coordinates for a merge ONLY at venue-level precision.
-- Existing rows are left null (precision unknown → they fall back to the text match, never a
-- coordinate-only merge); new promotions record 'venue' | 'area' from Nominatim's result class/type.
-- ===========================================================================================
alter table public.kisan_mela add column if not exists geocode_precision text;
