-- Batch 2 item F — Kisan Sawaal: English answer blocks + slug redirects.
--   1. answer_blocks_en (jsonb, nullable) — Batch 3 fills the English structured
--      answer; question_en / answer_en already exist.
--   2. kisan_sawaal_slug_redirects — old slug -> new (meaningful) slug, so the
--      legacy sawaal-* URLs keep working after re-slugging (client Navigate replace
--      + a _redirects 301 rule, both generated by scripts/sawaal-reslug.mjs).
--
-- SAFE FOR THE LIVE APP (Hard rule 8): kisan_sawaal is a V2-only table (migration
-- 0047); the pre-V2 live app has no Q&A. Purely additive — one nullable column and
-- one new table. Nothing renamed or made required.
-- Additive + idempotent.

alter table public.kisan_sawaal
  add column if not exists answer_blocks_en jsonb;

create table if not exists public.kisan_sawaal_slug_redirects (
  old_slug   text primary key,
  new_slug   text not null,
  created_at timestamptz not null default now()
);
alter table public.kisan_sawaal_slug_redirects enable row level security;

-- Public read (anon + authenticated): the client resolves an old slug to the new
-- one when a direct /sawaal/<old-slug> hit misses. Writes are service-role only
-- (the re-slug script), so no insert/update policy is granted.
drop policy if exists kisan_sawaal_redirects_read on public.kisan_sawaal_slug_redirects;
create policy kisan_sawaal_redirects_read on public.kisan_sawaal_slug_redirects
  for select to anon, authenticated using (true);
